arb-dir: lib/l10n/arb
output-dir: lib/l10n/gen
output-class: AppLocalizations
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
use-deferred-loading: true
nullable-getter: false