name: Gh-Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /One-Dungeon/
          webRenderer: "canvaskit"
          customArgs: --target lib/main_production.dart